### ISSUE TITLE
[Lisp]  `make` doesn't properly check for type coerence

### ISSUE THREAD

**Issue by spinnerwheel** [spinnerwheel/object-oriented#3]
Another error that I encountered while doing the same tests as #2 

```lisp
;; Define classes
(def-class 'person nil '(get-fields (name "Eve") (age 21)))

(def-class 'student '(person)
	    '(get-fields
	       (name "Eva Lu Ator")
	       (university "Bicocca" string))
	    '(methods
	       (talk (&optional (out *standard-output*))
		     (format out "My name is ~A~%My age is ~D~%"
			     (get-field this ’name)
			     (get-field this ’age)))))

```

I wanted to test the type checking capabilities and so I tried to create an instance with a **different type from** the one declared in **the class definition**.

Expetced behaviour
```lisp
prompt> (defparameter s1 'student 'university 1000)
;; NIL (or an error)
```

Actual behaviour
```lisp
prompt> (defparameter s1 (make 'student 'university 1000))
;; S1

prompt> (get-field s1 'university)
;; 1000
```

So the `make` method accepted an integer while the field `university` must be a **string** (as in the class definition)

**Comment by DavideNicoletta** [comment]
Fixed with commit 4e9a93e0a276a4443d9a1a512506a572a9c1f1e3
